# ***Mónica Alejandra Velasco Segura***

from rlrs.dqn import Memoria
from rlrs.redes import Red
from rlrs import GridWorld
from rlrs.redes import Adam 
import numpy as np

# 1. CONTROL 1: MEMORIA

# 1.1 Definimos los parámetros del entorno
capacidad = 10

# 1.2 Instanciamos nuestra Memoria
mem = Memoria(capacidad, 4)

# 1.3 Guardamos 12 transiciones que son 2 más de la capacidad

for i in range(12):
    mem.guardar(np.zeros(4), 0, 0.0, np.zeros(4), False)

# 1.4 Comprobamos el Control 1
print("\n--- Control 1: Memoria ---")
print(f"Capacidad máxima: {capacidad}")
print(f"Elementos guardados actualmente: {len(mem)}")
print(f"Índice interno actual (_i): {mem._i}")


#CONTROL 2: LOTE

#2.1 Extraemos un lote de tamaño 5
n_lote = 5
rgn = np.random.default_rng(seed=42)
# Usamos el método .lote() de la clase Memoria
s_lote, a_lote, r_lote, s2_lote, fin_lote = mem.lote(n_lote, rgn)

print("\n --- Control 2: Extracción de Lote ---")
print(f"Forma de s_lote: {s_lote.shape}")
print(f"Forma de a_lote: {a_lote.shape}")
print(f"¿Son los 5 arreglos del mismo tamaño?: {len(s_lote) == len(a_lote) == len(r_lote) == len(s2_lote) == len(fin_lote)}")

# Control 3: Red

#3.1 Definimos la arquitectura: 4 entradas, 64 ocultas, 4 salidas
d = 4
oculta = 64
n_acciones = 4
red = Red((d, oculta, n_acciones), seed=0)

#3.2 Probamos una sola entrada, es decir, un estado traducido.
x= np.array([1.0, 0.0, 0.0, 0.5556]) #estado 0
q_valores = red.adelante(x)

print("\n--- Control 3: Red ---")
print(f"Valores Q para el estado 0: {q_valores}")
print(f"Forma de la salida: {q_valores.shape}")

#3.3 Probamos con el lote que extrajimos antes (s_lote)
q_lote = red.adelante(s_lote)
print(f"Forma de la salida para el lote: {q_lote.shape}")

# Control 4: Aprendizaje (Actualización de los pesos), por medio de la ecuación de Bellman

#4.1 Parametros de Aprendizaje
gamma = 0.99

#4.2 Calculamos valores Q para el estado siguiente (s2)
q_s2 = red.adelante(s2_lote)

#4.3 Obtenemos el máximo valor Q para cada transición en el lote
max_q_s2 = np.max(q_s2, axis=1)

#4.4 Calculamos el Target (meta segun Bellman)
target = r_lote + gamma * max_q_s2 * (1 - fin_lote)

print("\n --- Control 4: Aprendizaje (Target) ---")
print(f"Valores de recompensa (r) : {r_lote}")
print(f"Valores objetivo (target): {target}")


# Control 5: Gradiente

#5.1 obtenemos las predicciones actuales de la red para el lote entero
q_actuales = red.adelante(s_lote)

#5.2 creamos una copia de las predicciones para modificar solo la accion tomada
#ya que solo quiero ajustar el valor Q de la acción que el agente realmente eligio
targets_completos = q_actuales.copy()

#5.3 insertamos el target segun la accion a_lote
for i in range(n_lote):
    targets_completos[i, a_lote[i]] = target [i]

#5.4 Calculamos el Gradiente (Error)
grad = targets_completos - q_actuales  #(prediccion - target)

print("\n--- Control 5: Gradiente ---")
print(f"Gradiente (primeras 2 filas): \n{grad[:2]}")

# --- Definición de la función de codificación (phi) ---
def phi(estado_idx):
    """
    Convierte el índice del estado (0-15) en un vector one-hot o representación 
    adecuada para la entrada de la red (tamaño 4).
    """
    # Si tu red espera 4 entradas, una forma común es un vector one-hot 
    # de tamaño 4 basado en el índice.
    v = np.zeros(4)
    # Ejemplo: dividimos el índice para mapearlo a 4 dimensiones
    v[int(estado_idx) % 4] = 1.0 
    return v

# --- Control 6: Bucle de Entrenamiento ---
# 1. Aseguramos la existencia del entorno (si lo definiste arriba, no hace falta redefinirlo)
entorno = GridWorld() 

# 2. Aseguramos el optimizador
optimizador = Adam(red.parametros(), lr=1e-3)

retornos = []
n_lote = 5 # Ajustado a tu capacidad de lote anterior
gamma = 0.99

print("\n--- Iniciando Control 6: Entrenamiento (300 episodios) ---")

for ep in range(300):
    s_raw, *otros = entorno.reset()
    s = phi(s_raw)
    
    retorno_total = 0
    terminado = False
    
    while not terminado:
        # Exploración Epsilon-Greedy
        if np.random.random() < 0.1:
            a = np.random.randint(4)
        else:
            # red.adelante devuelve (1,4), extraemos el vector
            a = np.argmax(red.adelante(s))

        print(f"DEBUG: El entorno devuelve {entorno.step(a)}")

        s2_raw, r, terminado, *otros = entorno.step(a)
        s2 = phi(s2_raw[0] if isinstance(s2_raw, tuple) else s2_raw)
        
        mem.guardar(s, a, r, s2, terminado)
        
        if len(mem) >= n_lote:
            s_lote, a_lote, r_lote, s2_lote, fin_lote = mem.lote(n_lote, rgn)
            
            # Bellman
            q_s2 = red.adelante(s2_lote)
            max_q_s2 = np.max(q_s2, axis=1)
            target = r_lote + gamma * max_q_s2 * (1 - fin_lote)
            
            # Gradiente
            q_actuales = red.adelante(s_lote)
            targets_completos = q_actuales.copy()
            for i in range(n_lote):
                targets_completos[i, int(a_lote[i])] = target[i]
            
            red.atras(targets_completos - q_actuales)
            optimizador.paso(red.parametros(), red.gradientes())
            
        s = s2
        retorno_total += r
        if retorno_total < -1000: break # Evitar bucles infinitos si no aprende
        
    retornos.append(retorno_total)
    if (ep + 1) % 50 == 0:
        print(f"Episodio {ep+1} | Retorno medio: {np.mean(retornos[-50:]):.4f}")

print(f"\nRetorno medio finales: {np.mean(retornos[-100:]):.4f}")
print(f"Norma final de los pesos: {red.norma():.4f}")

#RESULTADOS CONTROL 6

# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (7, -0.04, False, True, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (7, -0.04, False, True, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (16, -0.04, False, False, {'pos': (3, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (7, -0.04, False, False, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (7, -0.04, False, False, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (16, -0.04, False, False, {'pos': (3, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (16, -0.04, False, False, {'pos': (3, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (7, -0.04, False, False, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (12, -0.04, False, False, {'pos': (2, 2)})
# DEBUG: El entorno devuelve (7, -0.04, False, False, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (7, -0.04, False, True, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (7, -0.04, False, True, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (16, -0.04, False, False, {'pos': (3, 1)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (15, -0.04, False, False, {'pos': (3, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (15, -0.04, False, False, {'pos': (3, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (7, -0.04, False, False, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (8, -0.04, False, False, {'pos': (1, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (15, -0.04, False, False, {'pos': (3, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, True, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, True, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (12, -0.04, False, True, {'pos': (2, 2)})
# DEBUG: El entorno devuelve (8, -0.04, False, True, {'pos': (1, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (15, -0.04, False, False, {'pos': (3, 0)})
# DEBUG: El entorno devuelve (5, -0.04, False, False, {'pos': (1, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (16, -0.04, False, False, {'pos': (3, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (11, -0.04, False, False, {'pos': (2, 1)})
# DEBUG: El entorno devuelve (7, -0.04, False, False, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (7, -0.04, False, False, {'pos': (1, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (2, -0.04, False, True, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, True, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, True, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (3, -0.04, False, True, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (4, 1.0, True, False, {'pos': (0, 4)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# DEBUG: El entorno devuelve (10, -0.04, False, False, {'pos': (2, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (0, -0.04, False, False, {'pos': (0, 0)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (1, -0.04, False, False, {'pos': (0, 1)})
# DEBUG: El entorno devuelve (2, -0.04, False, False, {'pos': (0, 2)})
# DEBUG: El entorno devuelve (3, -0.04, False, False, {'pos': (0, 3)})
# Episodio 300 | Retorno medio: -0.9344

# Retorno medio finales: -0.8440
# Norma final de los pesos: 151.3615

# INTERPRETACIÒN
# 1. Retorno medio: Aunque es negativo, está muy cerca de cero. En muchos entornos de GridWorld, un valor cercano a cero indica que el agente está encontrando la meta con frecuencia, 
# pero todavía comete errores ocasionales o toma caminos largos. Ya no tenemos el $-4.0000$ que indica que el agente está perdido.
# 2. Norma final de los pesos ($|w| = 151.36$): Está en el orden de la centena/decena alta. Esto confirma que la red ha ajustado sus pesos significativamente a partir de la inicialización aleatoria.
# Lo que significa que el agente está aprendiendo: La diferencia entre $-4.0000$ y $-0.8440$ es enorme. El agente ha dejado de dar vueltas en círculos y está encontrando la meta.